name: FMHY Scraper

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # keeps GitHub Actions token for pushing

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Run Python scraper
        run: python main.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push master.json and snapshots
        run: |
          git add master.json snapshots/
          git commit -m "🔄 Auto-update master.json & daily snapshot [$(date '+%Y-%m-%d %H:%M:%S')]" || echo "No changes to commit"
          git push origin HEAD:main
